### PR TITLE
first draft of "Your First Experiment" doc

### PR DESCRIPTION
**Pull request by joshua-a-becker**

### CODE REVIEW

**Comment by joshua-a-becker** [comment]
a few minor fixes to be made to styling (URLs etc) and i have to check that all the code in the final draft is consistent with the final version of the demo app

demo app at https://github.com/joshua-a-becker/first-empirica-experiment

**Comment by amaatouq** [comment]
great thanks! I made a few changes to the code formatting (using `prettier` standards https://prettier.io/ ) and code block formatting using `js` .. Also, note that now we only game `game` in the `gameInit()` and accessing the `players` object and `treatment` object is always through `game`. Also, `var` should not be used but rather `const` or `let`

**Comment by joshua-a-becker** [comment]
great thanks i'll follow those standards moving forward---i totally knew about prettier but just forgot

RE: gameInit().... the current template still has all three game/treatment/players objects

**Comment by joshua-a-becker** [comment]
i'll circle back around tomorrow and update my git repo with Prettier & the other updates you made in the doc text

**Comment by joshua-a-becker** [comment]
references https://github.com/empiricaly/meteor-empirica-core/issues/32

**Comment by joshua-a-becker** [comment]
cool!  i've updated the repo, prettified, & pushed changes to github.com/joshua-a-becker

**Comment by joshua-a-becker** [comment]
working on it!  i'm a bit slow with github---as per @npaton's comment above i'm going to push to a branch, initiate a PR, we can review together, then merge

**Comment by amaatouq** [comment]
> working on it! i'm a bit slow with github---as per @npaton's comment above i'm going to push to a branch, initiate a PR, we can review together, then merge

perfect!

**Comment by joshua-a-becker** [comment]
alright took me a couple tries but there's a branch up w/ a PR waiting to be merged

**Comment by npaton** [comment]
Excellent! Thank you Joshua. I am unfortunately out until end of week so I won't be able to review this until beginning of next. I think I did notice one quick issue from the PR, it looks like the node_modules directory was committed. (https://gist.github.com/paulallies/0052fab554b14bbfa3ef). Sorry if I'm wrong, writing this on the go. ✈️

**Comment by amaatouq** [comment]
I'll merge this and we can iterate it on later (something is better than nothing).

**Pull request merged**
